# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lobby.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lobby.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blobby.proto\x12\x05lobby\"W\n\x10GameHistoryEntry\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x11\n\tgame_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x11\n\tmoney_won\x18\x04 \x01(\x05\"\x7f\n\x0cLobbyRequest\x12\"\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x12.lobby.LobbyAction\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08passhash\x18\x03 \x01(\t\x12\x14\n\x0cmoney_to_add\x18\x04 \x01(\x05\x12\x11\n\tgame_type\x18\x05 \x01(\x05\"\x96\x01\n\rLobbyResponse\x12\"\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x12.lobby.LobbyAction\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\x12\n\ngame_lobby\x18\x03 \x01(\t\x12-\n\x0cgame_history\x18\x04 \x03(\x0b\x32\x17.lobby.GameHistoryEntry\x12\x0e\n\x06moolah\x18\x05 \x01(\x05**\n\x0bLobbyAction\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nJOIN_LOBBY\x10\x01*.\n\x08GameType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TEXAS\x10\x01\x12\r\n\tFIVE_HAND\x10\x02\x32\x46\n\x0cLobbyService\x12\x36\n\x05Lobby\x12\x13.lobby.LobbyRequest\x1a\x14.lobby.LobbyResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lobby_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOBBYACTION']._serialized_start=393
  _globals['_LOBBYACTION']._serialized_end=435
  _globals['_GAMETYPE']._serialized_start=437
  _globals['_GAMETYPE']._serialized_end=483
  _globals['_GAMEHISTORYENTRY']._serialized_start=22
  _globals['_GAMEHISTORYENTRY']._serialized_end=109
  _globals['_LOBBYREQUEST']._serialized_start=111
  _globals['_LOBBYREQUEST']._serialized_end=238
  _globals['_LOBBYRESPONSE']._serialized_start=241
  _globals['_LOBBYRESPONSE']._serialized_end=391
  _globals['_LOBBYSERVICE']._serialized_start=485
  _globals['_LOBBYSERVICE']._serialized_end=555
# @@protoc_insertion_point(module_scope)
